services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - API_KEY=${API_KEY}
      - FRONTEND_URL=http://localhost

  frontend:
    build:
      context: ./FRONT
      args:
        VITE_API_URL: http://localhost:3001
    ports:
      - "80:80"
    depends_on:
      - backend
